services:
  backend:
    image: gcr.io/locusme/locusme-server:latest
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - main_db
      - cache_db
    # volumes:
    #   - ./backend:/app
    restart: always  

  main_db:
    image: postgres:15
    container_name: main_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    restart: always  


  cache_db:
    image: redis:alpine
    container_name: cache_db
    volumes:
      - redis_data:/data
    restart: always  

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #   restart: always  

volumes:
  postgres_data:
  redis_data:
