name: Deploy to GCE

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Google Compute Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > gce_key
          chmod 600 gce_key

      - name: Access Server via SSH and deploy
        run: |
          ssh -i gce_key -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_HOST }} << 'EOF'
            cd /ruta/de/tu/app
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d
          EOF
